openapi: 3.0.0
info:
  title: types related to location
  version: ${project.version}
servers: []
paths: {}
components:
  schemas:
    CountryNisCode:
      description: NIS code representing a country as defined by statbel.fgov.be
      type: integer
      minimum: 100
      maximum: 999
    MunicipalityCode:
      description: Numeric code to identify a Belgian municipality
      #municipality codes are the same in BeSt address and NIS code list
      type: integer
      minimum: 10000
      maximum: 99999