openapi: 3.0.0
info:
  title: types related to location
  version: "${project.version}-beta"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers: []
paths: {}
components:
  schemas: {}
    # TODO: other location types ~ BEST format and NR format