swagger: "2.0"
info:
  title: types related to location
  version: ${project.version}-beta
  #=> to debate: do we define CountryIso3166Alpha2Code?  or NationalityIsoCode?
paths: {}
definitions: {}
  # TODO: other location types ~ BEST format and NR format

