openapi: 3.0.0
info:
  title: types related to location
  version: v1
servers: []
paths: {}
components:
  schemas:
    CountryNisCode:
      description: NIS code representing a country as defined by statbel.fgov.be
      type: integer
      minimum: 100
      maximum: 999