swagger: "2.0"
info:
  title: types related to location
  version: ${project.version}
paths: {}
definitions:
  CountryNisCode:
    description: NIS code representing a country as defined by statbel.fgov.be
    type: integer
    minimum: 100
    maximum: 999